#-----------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Denis Astahov 2019.
#-----------------------------------
name: My-GitHubActions-Basics

on: 
  push:
    branches: 
      - master


jobs:
  my_testing:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Print nice message from Testing Job
        run : echo "Hello World from Test"
        
  my_deploy:
    runs-on: [ubuntu-latest]      
    
    steps:
      - name: Print nice message from Deploy Job
        run : echo "Hello World from Deploy"
